---
apiVersion: v1
kind: Namespace
metadata:
  name: collector

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: alloy
  namespace: collector
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: collector
spec:
  interval: 5m
  chart:
    spec:
      chart: alloy
      version: '0.10.1'
      sourceRef:
        kind: HelmRepository
        name: alloy
      interval: 5m
  values:
    controller:
      type: 'deployment'
    alloy:
      extraPorts:
        - name: "otlp-grpc"
          port: 4317
          targetPort: 4317
          protocol: "TCP"
        - name: "otlp-http"
          port: 4318
          targetPort: 4318
          protocol: "TCP"
      configMap:
        create: false
        name: alloy-config
        key: config.alloy